### ISSUE TITLE
Tests are failing!

### ISSUE THREAD

**Issue by Yaser-Amiri** [aio-libs/aiohttp-session#223]
Hi!
Tests of test_response_types.py arn't pass!
Is this problem just for me?
I'm using Python 3.5.2.

**Comment by asvetlov** [comment]
The build is passing on CI: https://travis-ci.org/aio-libs/aiohttp-session
Maybe you didn't upgrade aiohttp to 2.3+?

**Comment by asvetlov** [comment]
Just released 1.1 with upgraded requirements.

**Comment by Yaser-Amiri** [comment]
I'm using aiohttp 2.3.1!

`=============================================== test session starts ================================================
platform linux -- Python 3.5.2, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /home/yaser/GIT/sdf/aiohttp-session, inifile:
plugins: cov-2.5.1, aiohttp-0.1.3
collected 3 items                                                                                                   

test_response_types.py .FF

===================================================== FAILURES =====================================================
__________________________________________ test_bad_response_type[pyloop] __________________________________________

test_client = <function test_client.<locals>.go at 0x7f57397859d8>

    @asyncio.coroutine
    def test_bad_response_type(test_client):
    
        @asyncio.coroutine
        def bad_response(request):
            return ''
    
        middleware = session_middleware(SimpleCookieStorage())
        req = make_mocked_request('GET', '/')
        with pytest.raises(RuntimeError):
>           yield from middleware(req, bad_response)
E           Failed: DID NOT RAISE <class 'RuntimeError'>

test_response_types.py:45: Failed
--------------------------------------------- Captured stderr teardown ---------------------------------------------
Task exception was never retrieved
future: <Task finished coro=<test_bad_response_type() done, defined at /home/yaser/GIT/sdf/aiohttp-session/tests/test_response_types.py:35> exception=DID NOT RAISE <class 'RuntimeError'>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/_pytest/runner.py", line 196, in __init__
    self.result = func()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/runner.py", line 182, in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
    return call_outcome.get_result()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/runner.py", line 112, in pytest_runtest_call
    item.runtest()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/python.py", line 1169, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
    return call_outcome.get_result()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/pytest_plugin.py", line 160, in pytest_pyfunc_call
    _loop.run_until_complete(task)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 375, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1312, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/yaser/GIT/sdf/aiohttp-session/tests/test_response_types.py", line 45, in test_bad_response_type
    yield from middleware(req, bad_response)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/python_api.py", line 611, in __exit__
    fail(self.message)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/outcomes.py", line 85, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: DID NOT RAISE <class 'RuntimeError'>
_______________________________________ test_prepared_response_type[pyloop] ________________________________________

test_client = <function test_client.<locals>.go at 0x7f57367810d0>

    @asyncio.coroutine
    def test_prepared_response_type(test_client):
    
        @asyncio.coroutine
        def prepared_response(request):
            resp = web.Response()
            yield from resp.prepare(request)
            return resp
    
        middleware = session_middleware(SimpleCookieStorage())
        req = make_mocked_request('GET', '/')
        with pytest.raises(RuntimeError):
>           yield from middleware(req, prepared_response)
E           Failed: DID NOT RAISE <class 'RuntimeError'>

test_response_types.py:60: Failed
--------------------------------------------- Captured stderr teardown ---------------------------------------------
Task exception was never retrieved
future: <Task finished coro=<test_prepared_response_type() done, defined at /home/yaser/GIT/sdf/aiohttp-session/tests/test_response_types.py:48> exception=DID NOT RAISE <class 'RuntimeError'>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/_pytest/runner.py", line 196, in __init__
    self.result = func()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/runner.py", line 182, in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
    return call_outcome.get_result()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/runner.py", line 112, in pytest_runtest_call
    item.runtest()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/python.py", line 1169, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
    return call_outcome.get_result()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/usr/local/lib/python3.5/dist-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/pytest_plugin.py", line 160, in pytest_pyfunc_call
    _loop.run_until_complete(task)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 375, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1312, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/yaser/GIT/sdf/aiohttp-session/tests/test_response_types.py", line 60, in test_prepared_response_type
    yield from middleware(req, prepared_response)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/python_api.py", line 611, in __exit__
    fail(self.message)
  File "/usr/local/lib/python3.5/dist-packages/_pytest/outcomes.py", line 85, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: DID NOT RAISE <class 'RuntimeError'>
======================================== 2 failed, 1 passed in 0.09 seconds ========================================`

**Comment by Yaser-Amiri** [comment]
I'm using aiohttp 2.3.1 and aiohttp-session with commit number 74cc25cbec388fa1a6a7aefa20a2db0ef3d492a5 but problem exists yet.

traceback:
[https://paste.ubuntu.com/25880097/](url)

**Comment by panagiks** [comment]
Hm ... besides CI builds I just run the tests on Ubuntu 16.04/Py3.5.2 and everything is passing. Could you post the output of:
`pip list`

**Comment by Yaser-Amiri** [comment]
I'm using ubuntu 16.04 too!
pip3 list:
```
aiofiles (0.3.1)
aiohttp (2.3.1)
aiohttp-session (1.1.0, /home/yaser/GIT/sdf/aiohttp-session)
aiomcache (0.5.2)
aiopg (0.13.1)
aioredis (0.3.4)
alabaster (0.7.10)
apturl (0.5.2)
asn1crypto (0.23.0)
async-timeout (2.0.0)
Babel (2.5.1)
beautifulsoup4 (4.4.1)
blinker (1.3)
Brlapi (0.6.4)
cffi (1.11.2)
chardet (3.0.4)
checkbox-support (0.22)
click (6.7)
command-not-found (0.3)
coverage (4.4.1)
cryptography (2.1.2)
decorator (4.0.6)
defer (1.0.6)
docutils (0.14)
feedparser (5.1.3)
flake8 (3.5.0)
Flask (0.12.2)
Flask-C3chart (0.1)
Flask-JWT (0.3.2)
Flask-OAuth (0.12)
Flask-SQLAlchemy (2.2)
guacamole (0.9.2)
gunicorn (19.7.1)
hiredis (0.2.0)
html5lib (0.999)
httplib2 (0.9.1)
httptools (0.0.9)
idna (2.6)
imagesize (0.7.1)
influxdb (2.12.0)
ipython (2.4.1)
itsdangerous (0.24)
Jinja2 (2.9.6)
kazam (1.4.5)
language-selector (0.1)
louis (2.6.4)
lxml (3.5.0)
Mako (1.0.3)
MarkupSafe (1.0)
mccabe (0.6.1)
multidict (3.3.0)
oauth2 (1.9.0.post1)
oauthlib (1.0.3)
onboard (1.2.0)
padme (1.1.1)
pep257 (0.7.0)
pexpect (4.0.1)
pika (0.10.0)
Pillow (3.1.2)
pip (8.1.1)
plainbox (0.25)
psutil (3.4.2)
psycopg2 (2.7.3.1)
ptyprocess (0.5)
py (1.4.34)
pyasn1 (0.1.9)
pycodestyle (2.2.0)
pycparser (2.18)
pycups (1.9.73)
pycurl (7.43.0)
pyflakes (1.5.0)
pygame (1.9.3)
Pygments (2.2.0)
pygobject (3.20.0)
PyJWT (1.4.2)
PyNaCl (1.1.2)
pyparsing (2.0.3)
pyTelegramBotAPI (2.3.0)
pytest (3.2.3)
pytest-aiohttp (0.1.3)
pytest-cov (2.5.1)
python-apt (1.1.0b1)
python-dateutil (2.4.2)
python-debian (0.1.27)
python-systemd (231)
pytz (2014.10)
pyxdg (0.25)
redis (2.10.5)
reportlab (3.3.0)
requests (2.9.1)
sanic (0.6.0)
sanic-jinja2 (0.5.5)
selenium (3.0.2)
sessioninstaller (0.0.0)
setuptools (20.7.0)
short-url (1.2.2)
simplegeneric (0.8.1)
six (1.10.0)
snowballstemmer (1.2.1)
Sphinx (1.6.5)
sphinxcontrib-websupport (1.0.1)
SQLAlchemy (1.1.13)
ssh-import-id (5.5)
system-service (0.3)
ubuntu-drivers-common (0.0.0)
ufw (0.35)
ujson (1.35)
unattended-upgrades (0.1)
unity-scope-calculator (0.1)
unity-scope-chromiumbookmarks (0.1)
unity-scope-colourlovers (0.1)
unity-scope-devhelp (0.1)
unity-scope-firefoxbookmarks (0.1)
unity-scope-gdrive (0.7)
unity-scope-manpages (0.1)
unity-scope-openclipart (0.1)
unity-scope-texdoc (0.1)
unity-scope-tomboy (0.1)
unity-scope-virtualbox (0.1)
unity-scope-yelp (0.1)
unity-scope-zotero (0.1)
unpyclib (0.8.1)
urllib3 (1.13.1)
usb-creator (0.3.0)
uvloop (0.8.1)
validators (0.12.0)
virtualenv (15.0.3)
websockets (3.4)
Werkzeug (0.12.2)
wheel (0.29.0)
xdiagnose (3.8.4.1)
xkit (0.0.0)
XlsxWriter (0.7.3)
yarl (0.13.0)
```

**Comment by panagiks** [comment]
Two things that might help:
* Do a `git status` and make sure that you are working on a clean copy (there are no changes)
** If you have made any changes do a `git stash` run the tests and then `git stash apply` and rerun them (to make sure that any changes don't affect the outcome of the tests)
* Create a virtualenv and pip install the requirements-dev.txt inside the virtualenv (To make sure that the tests are not influenced by any other installed package and to be able to upgrade some packages, i.e. setuptools, that are a bit old without interfering with your system's python installation)

**Comment by Yaser-Amiri** [comment]
I cloned a new instance and ran it in another virtualenv but no change happened.
So I created another virtualenv in a virtual machine and all tests passed amazingly :/
Sorry and thank bro.
