### ISSUE TITLE
redis storage error

### ISSUE THREAD

**Issue by dobrovolsky** [aio-libs/aiohttp-session#240]
Hi, i have some error when add value to session.
```python
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/ubuntu/chat/env/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 410, in start
    resp = yield from self._request_handler(request)
  File "/home/ubuntu/chat/env/lib/python3.6/site-packages/aiohttp/web.py", line 326, in _handle
    resp = yield from handler(request)
  File "/home/ubuntu/chat/env/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 93, in impl
    return (yield from handler(request))
  File "/home/ubuntu/chat/env/lib/python3.6/site-packages/aiohttp_session/__init__.py", line 144, in middleware
    yield from storage.save_session(request, response, session)
  File "/home/ubuntu/chat/env/lib/python3.6/site-packages/aiohttp_session/redis_storage.py", line 60, in save_session
    with (yield from self._redis) as conn:
TypeError: 'ConnectionsPool' object is not iterable
```

**Comment by panagiks** [comment]
Hello. Could you please provide the output of `pip list`? From a quick look at the traceback it seems like you are running an older version of `aiohttp-session` (since the `yield from` syntax has been dropped in latest versions).

**Comment by dobrovolsky** [comment]
Thank you for quick replay 
```aiohttp (2.3.5)
aiohttp-jinja2 (0.14.0)
aiohttp-session (1.0.1)
aioredis (1.0.0)
async-timeout (2.0.0)
chardet (3.0.4)
envparse (0.2.0)
gunicorn (19.7.1)
hiredis (0.2.0)
Jinja2 (2.9.6)
MarkupSafe (1.0)
marshmallow (2.13.6)
motor (1.1)
multidict (3.3.2)
pip (9.0.1)
pymongo (3.5.1)
setuptools (38.2.3)
uvloop (0.8.1)
wheel (0.30.0)
yarl (0.15.0)
```

**Comment by panagiks** [comment]
Ah, as I suspected. `aiohttp-session` is in a relatively old version (current version being `2.1.0`) and your `aioredis` is in version `1.0.0` which is supported in `aiohttp-session` after `2.0.0`. 

I'd suggest either updating `aiohttp-session` (`pip install -U aiohttp-session`) or installing a version of `aioredis<1.0.0`. I think the first would be the safest bet.

**Comment by jettify** [comment]
@panagiks thank you for helping to resolve this issue!
