### ISSUE TITLE
Python 3.7 EncryptedCookieStorage Error: Incorrect padding

### ISSUE THREAD

**Issue by congnghiakhiem** [aio-libs/aiohttp-session#333]
Traceback (most recent call last):
  File "app.py", line 60, in <module>
    serv_generator, handler, app = loop.run_until_complete(init(loop))
  File "C:\Python37\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "app.py", line 34, in init
    session_middleware(EncryptedCookieStorage(SECRET_KEY)),
  File "C:\Python37\lib\site-packages\aiohttp_session\cookie_storage.py", line 28, in __init__
    self._fernet = fernet.Fernet(secret_key)
  File "C:\Python37\lib\site-packages\cryptography\fernet.py", line 34, in __init__
    key = base64.urlsafe_b64decode(key)
  File "C:\Python37\lib\base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "C:\Python37\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by panagiks** [comment]
Hello @congnghiakhiem ,

this seems to be an issue with the `SECRET_KEY`. Could you please verify that your `SECRET_KEY` conforms with Fernet expectation (i.e. consists of 32 base64-encoded bytes) ? An easy way would be to put these two lines before `session_middleware(EncryptedCookieStorage(SECRET_KEY))`:

```py
print(type(SECRET_KEY))
print(len(SECRET_KEY))
```

The result should be:

```
<class 'bytes'>
32
```

Regards.

**Comment by congnghiakhiem** [comment]
Thank you. I found the way.

To generate SECRET_KEY
```
from cryptography import fernet
fernet_key = fernet.Fernet.generate_key().decode("utf-8")
```
